export const CUISINES = [
  { name: 'Mexican',      flag: '🇲🇽', slug: 'mexican' },
  { name: 'Japanese',     flag: '🇯🇵', slug: 'japanese' },
  { name: 'Indian',       flag: '🇮🇳', slug: 'indian' },
  { name: 'French',       flag: '🇫🇷', slug: 'french' },
  { name: 'Thai',         flag: '🇹🇭', slug: 'thai' },
  { name: 'Italian',      flag: '🇮🇹', slug: 'italian' },
  { name: 'Chinese',      flag: '🇨🇳', slug: 'chinese' },
  { name: 'Greek',        flag: '🇬🇷', slug: 'greek' },
  { name: 'Spanish',      flag: '🇪🇸', slug: 'spanish' },
  { name: 'Moroccan',     flag: '🇲🇦', slug: 'moroccan' },
  { name: 'Lebanese',     flag: '🇱🇧', slug: 'lebanese' },
  { name: 'Korean',       flag: '🇰🇷', slug: 'korean' },
  { name: 'Vietnamese',   flag: '🇻🇳', slug: 'vietnamese' },
  { name: 'Turkish',      flag: '🇹🇷', slug: 'turkish' },
  { name: 'Brazilian',    flag: '🇧🇷', slug: 'brazilian' },
  { name: 'Peruvian',     flag: '🇵🇪', slug: 'peruvian' },
  { name: 'Ethiopian',    flag: '🇪🇹', slug: 'ethiopian' },
  { name: 'American',     flag: '🇺🇸', slug: 'american' },
  { name: 'British',      flag: '🇬🇧', slug: 'british' },
  { name: 'German',       flag: '🇩🇪', slug: 'german' },
  { name: 'Caribbean',    flag: '🌴', slug: 'caribbean' },
  { name: 'Middle Eastern', flag: '🌙', slug: 'middle-eastern' },
  { name: 'Argentinian',  flag: '🇦🇷', slug: 'argentinian' },
  { name: 'Indonesian',   flag: '🇮🇩', slug: 'indonesian' },
  { name: 'Filipino',     flag: '🇵🇭', slug: 'filipino' },
  { name: 'Polish',       flag: '🇵🇱', slug: 'polish' },
  { name: 'Portuguese',   flag: '🇵🇹', slug: 'portuguese' },
  { name: 'Cuban',        flag: '🇨🇺', slug: 'cuban' },
  { name: 'Haitian',      flag: '🇭🇹', slug: 'haitian' },
  { name: 'Israeli',      flag: '🇮🇱', slug: 'israeli' },
];

export const FEATURED_RECIPES = [
  {
    slug: 'lamb-tagine',
    title: 'Lamb Tagine',
    cuisine: 'Moroccan',
    course: 'Main',
    total_time: '2h 30min',
    photo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&q=80',
  },
  {
    slug: 'miso-ramen',
    title: 'Miso Ramen',
    cuisine: 'Japanese',
    course: 'Main',
    total_time: '45 min',
    photo: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80',
  },
  {
    slug: 'shakshuka',
    title: 'Shakshuka',
    cuisine: 'Middle Eastern',
    course: 'Breakfast',
    total_time: '25 min',
    photo: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600&q=80',
  },
  {
    slug: 'pad-thai',
    title: 'Pad Thai',
    cuisine: 'Thai',
    course: 'Main',
    total_time: '30 min',
    photo: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80',
  },
  {
    slug: 'ceviche',
    title: 'Peruvian Ceviche',
    cuisine: 'Peruvian',
    course: 'Starter',
    total_time: '20 min',
    photo: 'https://images.unsplash.com/photo-1535400255456-984e0a8e3bf8?w=600&q=80',
  },
  {
    slug: 'tiramisu',
    title: 'Tiramisu',
    cuisine: 'Italian',
    course: 'Dessert',
    total_time: '4h (incl. chill)',
    photo: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
  },
];
